os: linux
dist: focal
language: php

php:
    - 7.4
    - 8.0
    - 8.1
    - nightly

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: 5.3
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
          dist: trusty
        - php: 5.5
          dist: trusty
        - php: 5.6
          dist: trusty
        - php: 7.0
          dist: xenial
        - php: 7.1
          dist: xenial
        - php: 7.2
          dist: xenial
        - php: 7.3
          dist: xenial


services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install --prefer-dist --no-progress --no-suggest -o

script:
  - "cd tests && php -dshort_open_tag=Off -dmagic_quotes_gpc=Off run.php"
